name: Daily Data Sync

on:
  schedule:
    - cron: '0 3 * * *'  # Trigger otomatis setiap hari jam 03:00 UTC
  workflow_dispatch:     # Memungkinkan trigger manual dari UI GitHub

jobs:
  sync-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r src/requirements.txt

      - name: Run sync
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          SATKER: ${{ secrets.SATKER }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          python src/main.py

      - name: Check env vars
        run: |
          echo "GOOGLE_CREDENTIALS length: ${#GOOGLE_CREDENTIALS}"

      - name: Prepare Docs Folder
        run: |
          mkdir -p docs
          cp report.html docs/
          touch docs/.nojekyll
          ls -la docs/  # Debugging: cek isi folder

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages  # Nama harus sama dengan download di deploy.yml
          path: docs/
          retention-days: 1

  deploy:
    needs: [sync-data]
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
